<?php

namespace Database\Seeders;

use App\Models\FundraisingOpportunity;
use Illuminate\Database\Seeder;

class FundraisingMasterSeeder extends Seeder
{
    public function run(): void
    {
        $opportunities = [
            // Sheet 1: Open Calls
            [
                'organization' => 'Wildlife Fund',
                'program_title' => 'Dierenpark Amersfoort Wildlife Fund',
                'application_link' => 'https://wildlifefund.nl/en/submit-project/',
                'amount_kes' => 753250.00,
                'amount_display' => 'KES 753,250',
                'funding_type' => 'Grant',
                'deadline' => 'Oct 31',
                'status' => 'In Progress',
                'category' => 'open_calls',
                'notes' => 'Partnership required to close proposal.',
            ],
            [
                'organization' => 'D-Prize',
                'program_title' => 'Custom Solution Challenge',
                'application_link' => 'https://d-prize.org/',
                'amount_kes' => 2588000.00,
                'amount_display' => 'KES 2,588,000',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 15',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Application submitted successfully.',
            ],
            [
                'organization' => 'OneYoungWorld',
                'program_title' => 'The NewNow Scholarship',
                'application_link' => 'https://www.oneyoungworld.com/scholarship/newnow',
                'amount_kes' => 0.00,
                'amount_display' => 'Capacity-building',
                'funding_type' => 'Fellowship',
                'deadline' => 'Nov 20',
                'status' => 'Identified',
                'category' => 'fellowships',
                'notes' => 'Youth media scholarship and global leadership fellowship.',
            ],
            [
                'organization' => 'Goethe-Institut & Expertise France',
                'program_title' => 'The Connect and Create Programme',
                'application_link' => 'https://www.ifprog.emundus.fr/en/campagne-info?view=programme&cid=301',
                'amount_kes' => 9039000.00,
                'amount_display' => 'KES 9,039,000',
                'funding_type' => 'Grant',
                'deadline' => 'Oct 28',
                'status' => 'In Progress',
                'category' => 'open_calls',
                'notes' => 'Creative industries and digital storytelling program.',
            ],
            [
                'organization' => 'Global Citizen',
                'program_title' => 'Cisco Youth Leadership Award',
                'application_link' => 'https://www.globalcitizen.org/en/prize/youth-leadership/',
                'amount_kes' => 32338041.00,
                'amount_display' => 'KES 32,338,041',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 01',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Youth leadership prize in media & environmental technology.',
            ],
            [
                'organization' => 'Social Shifters',
                'program_title' => 'MoveNow Global Social Innovation Challenge',
                'application_link' => 'https://www.socialshifters.co/global-innovation-challenge/allianz-movenow/',
                'amount_kes' => 1292990.00,
                'amount_display' => 'KES 1,292,990',
                'funding_type' => 'Competition',
                'deadline' => 'Oct 25',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Social innovation & creative entrepreneurship.',
            ],
            [
                'organization' => 'Government of the Netherlands',
                'program_title' => 'FemFocus 2026–2030',
                'application_link' => 'https://www.government.nl/topics/grant-programmes/femfocus-2026-2030',
                'amount_kes' => 412781000.00,
                'amount_display' => 'KES 412,781,000',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 18',
                'status' => 'Missed',
                'category' => 'open_calls',
                'notes' => 'Large scale multi-year consortium funding.',
            ],
            [
                'organization' => 'Obama Foundation',
                'program_title' => 'Leaders Africa Program',
                'application_link' => 'https://www.obama.org/programs/leaders/',
                'amount_kes' => 0.00,
                'amount_display' => 'Capacity-building',
                'funding_type' => 'Fellowship',
                'deadline' => 'Oct 25',
                'status' => 'Submitted',
                'category' => 'fellowships',
                'notes' => 'African leadership network and executive mentorship.',
            ],
            [
                'organization' => 'AU-EU Youth Action Lab',
                'program_title' => 'Entrepreneurship Grants',
                'application_link' => 'https://aueuyouth.com/entrepreneurship-grants/',
                'amount_kes' => 4519500.00,
                'amount_display' => 'KES 4,519,500',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 18',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'partner_organization' => 'Kilimora CLG',
                'notes' => 'Submitted in partnership with Kilimora CLG (Non-profit entity).',
            ],
            [
                'organization' => 'Villgro Africa',
                'program_title' => 'Eye Health Accelerator',
                'application_link' => 'https://vc4a.com/villgro-africa/eye-health-accelerator-call-for-applications/#edit-page-content',
                'amount_kes' => 32338050.00,
                'amount_display' => 'KES 32,338,050',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 25',
                'status' => 'In Progress',
                'partner_organization' => 'Pankaj Social Service (Kenya Eye Project)',
                'notes' => 'Partnering with Pankaj Social Service on Kenya Eye documentary series.',
            ],
            [
                'organization' => 'Kenya Climate Innovation Center (KCIC)',
                'program_title' => 'Sheria Ya Vijana Project (SYV)',
                'application_link' => 'https://www.kenyacic.org/sheria-ya-vijana/#1763525960406-69e9e843-797e',
                'amount_kes' => 0.00,
                'amount_display' => 'Capacity-building',
                'funding_type' => 'Capacity-building',
                'deadline' => 'Nov 02',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Climate law, youth advocacy, and media reporting.',
            ],
            [
                'organization' => 'Business & Human Rights Resource Centre (BHRRC)',
                'program_title' => 'CSOs: Just Transition to Green Economies',
                'application_link' => 'https://www.business-humanrights.org/en/latest-news/call-for-proposals-csos-in-kenya-south-africa-indonesia-and-the-philippines-advancing-a-just-rights-based-transition-to-green-economies/',
                'amount_kes' => 13170000.00,
                'amount_display' => 'KES 13,170,000',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 23',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Just transition storytelling and investigative media series.',
            ],
            [
                'organization' => 'Catchlight',
                'program_title' => 'Global Fellowship in Visual Storytelling',
                'application_link' => 'https://www.catchlight.io/how-to-apply-global-fellowship',
                'amount_kes' => 3880566.00,
                'amount_display' => 'KES 3,880,566',
                'funding_type' => 'Fellowship',
                'deadline' => 'Nov 02',
                'status' => 'Submitted',
                'category' => 'fellowships',
                'notes' => 'Visual journalism and social impact photography fellowship.',
            ],
            [
                'organization' => 'New Africa Fund',
                'program_title' => 'Africa Impact Fundraising (AIF) Grant Program',
                'application_link' => 'https://www.newafricafund.org/aifgrants',
                'amount_kes' => 646761.00,
                'amount_display' => 'KES 646,761',
                'funding_type' => 'Grant',
                'deadline' => 'Oct 30',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Direct grassroots impact storytelling grant.',
            ],
            [
                'organization' => 'DO School',
                'program_title' => 'beVisioneers: The Mercedes-Benz Fellowship',
                'application_link' => 'https://applications.bevisioneers.world/',
                'amount_kes' => 2586000.00,
                'amount_display' => 'KES 2,586,000',
                'funding_type' => 'Fellowship',
                'deadline' => 'Dec 05',
                'status' => 'Submitted',
                'category' => 'fellowships',
                'notes' => 'Sustainability innovation & climate media production.',
            ],
            [
                'organization' => 'Prince Claus Fund',
                'program_title' => 'Seed Award 2026',
                'application_link' => 'https://princeclausfund.nl/awards-and-programmes/seed-award/2026-call-for-applications',
                'amount_kes' => 644300.00,
                'amount_display' => 'KES 644,300',
                'funding_type' => 'Grant',
                'deadline' => 'Nov 19',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Arts, culture, and social transformation seed grant.',
            ],
            [
                'organization' => 'Rufford Foundation',
                'program_title' => 'Rufford Small Grant for Conservation',
                'application_link' => 'https://apply.ruffordsmallgrants.org/',
                'amount_kes' => 1056510.00,
                'amount_display' => 'KES 1,056,510',
                'funding_type' => 'Grant',
                'deadline' => 'Rolling basis',
                'status' => 'In Progress',
                'category' => 'open_calls',
                'notes' => 'Nature conservation documentary storytelling grant.',
            ],
            [
                'organization' => 'Pulitzer Center',
                'program_title' => 'Environment & Climate Reporting Grants',
                'application_link' => 'https://pulitzercenter.org/grants-fellowships/opportunities-journalists/our-work-environment-grants',
                'amount_kes' => 2575800.00,
                'amount_display' => 'KES 2,575,800',
                'funding_type' => 'Grant',
                'deadline' => 'Rolling basis',
                'status' => 'In Progress',
                'category' => 'open_calls',
                'partner_organization' => 'Kilimora CLG',
                'notes' => 'Investigative reporting grant on East African environmental governance.',
            ],
            [
                'organization' => 'The Global Good Fund',
                'program_title' => 'The Global Good Fund Fellowship 2027',
                'application_link' => 'https://menterprise.africa/opportunities/global-good-fund-fellowship-2027/',
                'amount_kes' => 64725000.00,
                'amount_display' => 'KES 64,725,000',
                'funding_type' => 'Fellowship',
                'deadline' => 'May 10',
                'status' => 'Submitted',
                'category' => 'fellowships',
                'notes' => 'Social entrepreneurs and media leaders scale fellowship.',
            ],
            [
                'organization' => 'AU-EU Youth Voices Lab',
                'program_title' => 'Lens of Change — Call for Young Filmmakers',
                'application_link' => 'https://aueuyouthvoiceslab.eu/lens-of-change-open-call-for-young-filmmakers/',
                'amount_kes' => 267084.00,
                'amount_display' => 'KES 267,084',
                'funding_type' => 'Grant',
                'deadline' => 'May 08',
                'status' => 'Submitted',
                'category' => 'open_calls',
                'notes' => 'Short documentary film production grant.',
            ],

            // Sheet 3: Partnership Exploration (Separated Institutional & CBO Exploration)
            // a. Grantmakers / CBOs
            [
                'organization' => 'Oak Foundation',
                'program_title' => 'Grants & Environment Programme',
                'application_link' => 'https://oakfnd.org/submit-enquiry/',
                'amount_kes' => 15000000.00,
                'amount_display' => 'KES 15,000,000',
                'funding_type' => 'Grants Application',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Initial inquiry submitted for conservation & human rights media.',
            ],
            [
                'organization' => 'Institut für Auslandsbeziehungen (ifa)',
                'program_title' => 'Zivik Conflict Resolution & Media Funding',
                'application_link' => 'https://www.ifa.de/en/funding/zivik/',
                'amount_kes' => 12500000.00,
                'amount_display' => 'KES 12,500,000',
                'funding_type' => 'Grants Application',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Zivik funding programme for civil conflict resolution and documentary storytelling.',
            ],
            [
                'organization' => 'Draper Richards Kaplan Foundation',
                'program_title' => 'Venture Philanthropy Partnership',
                'application_link' => 'https://www.drkfoundation.org/apply-for-funding/',
                'amount_kes' => 45000000.00,
                'amount_display' => 'KES 45,000,000',
                'funding_type' => 'Grants Application',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Social enterprise scaling and creative ecosystem building.',
            ],
            [
                'organization' => 'SwedBio',
                'program_title' => 'Collaborative Programme in Biodiversity',
                'application_link' => 'https://swedbio/collaborative-programme/applicat',
                'amount_kes' => 18000000.00,
                'amount_display' => 'KES 18,000,000',
                'funding_type' => 'Grants Application',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Biodiversity and local knowledge systems media support.',
            ],
            [
                'organization' => 'Charles Stewart Mott Foundation',
                'program_title' => 'Civil Society & Community Media',
                'application_link' => 'https://www.mott.org/what-we-fund/',
                'amount_kes' => 20000000.00,
                'amount_display' => 'KES 20,000,000',
                'funding_type' => 'Grants Application',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Community storytelling and public media engagement.',
            ],
            [
                'organization' => 'Synergos',
                'program_title' => 'Global Philanthropic Partnership',
                'application_link' => 'https://www.synergos.org/',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Direct outreach',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Global philanthropic network for collaborative systemic change.',
            ],
            [
                'organization' => 'Lemelson Foundation',
                'program_title' => 'Invention Education & Storytelling',
                'application_link' => 'https://lemelson.formtitan.com/eqt/',
                'amount_kes' => 25000000.00,
                'amount_display' => 'KES 25,000,000',
                'funding_type' => 'Grants Application',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Grantmakers / CBOs',
                'notes' => 'Invention education and climate-focused storytelling.',
            ],

            // b. Associations / Cooperatives
            [
                'organization' => 'Kenya Union of Hairdressers and Beauticians (KUHB)',
                'program_title' => 'Creative Trade Skills & Vocational Storytelling',
                'application_link' => 'https://kuhb.co.ke',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Associations / Cooperatives',
                'notes' => 'Vocational impact storytelling & creative trade partnerships.',
            ],
            [
                'organization' => 'National Farmers Cooperative Union',
                'program_title' => 'Agritech & Smallholder Farmer Docuseries',
                'application_link' => 'https://farmerscoop.ke',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Associations / Cooperatives',
                'notes' => 'Agritech & regenerative agriculture docuseries outreach.',
            ],
            [
                'organization' => 'Kenya Community Media Network (KCOMNET)',
                'program_title' => 'Grassroots Civic Media Syndication',
                'application_link' => 'https://kcomnet.org',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Associations / Cooperatives',
                'notes' => 'Grassroots civic journalism & community media syndication.',
            ],

            // c. Corporate Institutions
            [
                'organization' => 'Altérra',
                'program_title' => 'Climate Transition & Clean Energy Media',
                'application_link' => 'https://www.alterra.ae/contact-us',
                'amount_kes' => 50000000.00,
                'amount_display' => 'KES 50,000,000',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Direct outreach',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Corporate Institutions',
                'notes' => 'Institutional climate transition fund outreach for regional green energy films.',
            ],
            [
                'organization' => 'Safaricom Foundation',
                'program_title' => 'Digital Inclusion & Community Storytelling',
                'application_link' => 'https://www.safaricomfoundation.org/',
                'amount_kes' => 30000000.00,
                'amount_display' => 'KES 30,000,000',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Corporate Institutions',
                'notes' => 'Digital inclusion and community empowerment partnerships.',
            ],
            [
                'organization' => 'KCB Foundation',
                'program_title' => '2Jiajiri Youth Enterprise & Creative Arts',
                'application_link' => 'https://kcbgroup.com/foundation/',
                'amount_kes' => 20000000.00,
                'amount_display' => 'KES 20,000,000',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Rolling basis',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Corporate Institutions',
                'notes' => '2Jiajiri youth enterprise and creative capacity building.',
            ],

            // d. Academia / Educational Institutions
            [
                'organization' => 'Strathmore University Business School (SBS)',
                'program_title' => 'Executive Media Lab & Climate Governance',
                'application_link' => 'https://sbs.strathmore.edu/',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Academic calendar',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Academia / Educational Institutions',
                'notes' => 'Executive media lab & climate governance research collaboration.',
            ],
            [
                'organization' => 'University of Nairobi Media Lab',
                'program_title' => 'Youth Journalism Training & Investigative Studio',
                'application_link' => 'https://journalism.uonbi.ac.ke/',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Academic calendar',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Academia / Educational Institutions',
                'notes' => 'Youth journalism training and collaborative investigative productions.',
            ],
            [
                'organization' => 'Aga Khan University Graduate School of Media (GSMC)',
                'program_title' => 'Environmental Reporting Fellowship',
                'application_link' => 'https://www.aku.edu/gsmc',
                'amount_kes' => 0.00,
                'amount_display' => 'Partnership',
                'funding_type' => 'Partnership Invitation',
                'deadline' => 'Annual call',
                'status' => 'Pending',
                'category' => 'partnerships',
                'partnership_entity_type' => 'Academia / Educational Institutions',
                'notes' => 'Environmental reporting fellowship and masterclass curriculum partnership.',
            ],
        ];

        foreach ($opportunities as $opp) {
            FundraisingOpportunity::updateOrCreate(
                ['organization' => $opp['organization']],
                $opp
            );
        }
    }
}
