<?php

namespace App\Http\Controllers\Api\Ai;

use App\Http\Controllers\Controller;
use App\Models\AiReport;
use App\Services\Ai\GeminiReportService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class AiReportController extends Controller
{
    public function __construct(
        protected GeminiReportService $reportService
    ) {}

    /**
     * Generate or fetch a cached AI executive / financial / project report.
     */
    public function generate(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'report_type' => 'nullable|string|in:executive_digest,financial_summary,project_status',
            'refresh' => 'nullable|boolean',
        ]);

        $reportType = $validated['report_type'] ?? 'executive_digest';
        $forceRefresh = (bool) ($validated['refresh'] ?? false);
        $user = $request->user();

        if (! $user) {
            return response()->json(['status' => 'error', 'message' => 'Unauthenticated.'], 401);
        }

        $report = $this->reportService->generateReport($user, $reportType, $forceRefresh);

        return response()->json($report);
    }

    /**
     * List previous reports generated by or for the user.
     */
    public function history(Request $request): JsonResponse
    {
        $user = $request->user();
        if (! $user) {
            return response()->json(['status' => 'error', 'message' => 'Unauthenticated.'], 401);
        }

        $query = AiReport::latest('created_at')->take(20);

        if ($user->role !== 'owner') {
            $query->where('user_id', $user->id);
        }

        $reports = $query->get()->map(function (AiReport $r) {
            return [
                'id' => $r->id,
                'report_type' => $r->report_type,
                'user_role' => $r->user_role,
                'model_used' => $r->model_used,
                'summary_snippet' => Str::limit($r->summary_content, 180),
                'created_at' => $r->created_at?->toIso8601String(),
            ];
        });

        return response()->json([
            'status' => 'success',
            'reports' => $reports,
        ]);
    }
}
