<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ $subject ?? 'JMOS Notification — Jeota Media' }}</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #FAF7F6;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #1C1614;
      -webkit-font-smoothing: antialiased;
    }
    .wrapper {
      width: 100%;
      table-layout: fixed;
      background-color: #FAF7F6;
      padding: 30px 10px;
    }
    .container {
      max-width: 580px;
      margin: 0 auto;
      background-color: #FFFFFF;
      border-radius: 14px;
      overflow: hidden;
      border: 1px solid #ECE6E4;
      box-shadow: 0 4px 20px rgba(28, 22, 20, 0.06);
    }
    .header {
      background: linear-gradient(135deg, #E23A2E 0%, #9E1B21 100%);
      padding: 30px;
      text-align: left;
    }
    .brand-title {
      color: #FFFFFF;
      font-size: 20px;
      font-weight: 700;
      letter-spacing: 0.05em;
      margin: 0;
      display: inline-block;
    }
    .brand-sub {
      color: #FFE5E2;
      font-size: 11px;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      margin-top: 3px;
    }
    .content {
      padding: 32px 30px;
    }
    .headline {
      font-size: 20px;
      font-weight: 700;
      color: #1C1614;
      margin: 0 0 14px 0;
    }
    .body-text {
      font-size: 14.5px;
      line-height: 1.6;
      color: #4A4340;
      margin: 0 0 20px 0;
    }
    .info-card {
      background-color: #FAF7F6;
      border: 1px solid #ECE6E4;
      border-radius: 10px;
      padding: 18px 20px;
      margin-bottom: 24px;
    }
    .info-row {
      display: flex;
      justify-content: space-between;
      padding: 7px 0;
      border-bottom: 1px dashed #ECE6E4;
      font-size: 13.5px;
    }
    .info-row:last-child {
      border-bottom: none;
      padding-bottom: 0;
    }
    .info-label {
      color: #6E6763;
      font-weight: 500;
    }
    .info-val {
      color: #1C1614;
      font-weight: 600;
      text-align: right;
    }
    .badge {
      display: inline-block;
      padding: 4px 9px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 600;
    }
    .badge-red {
      background-color: #FBEAE8;
      color: #C52523;
    }
    .badge-green {
      background-color: #E4F1EA;
      color: #1C7A4E;
    }
    .badge-amber {
      background-color: #FAEDD3;
      color: #B4780F;
    }
    .btn-action {
      display: inline-block;
      background-color: #C52523;
      color: #FFFFFF !important;
      text-decoration: none;
      font-size: 14px;
      font-weight: 600;
      padding: 12px 24px;
      border-radius: 8px;
      margin-top: 8px;
      text-align: center;
    }
    .footer {
      background-color: #FAF7F6;
      border-top: 1px solid #ECE6E4;
      padding: 24px 30px;
      text-align: center;
      font-size: 12px;
      color: #9A928E;
      line-height: 1.5;
    }
    .footer strong {
      color: #6E6763;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <!-- Header -->
      <div class="header">
        <div class="brand-title">JEOTA MEDIA</div>
        <div class="brand-sub">OPERATING SYSTEM · JMOS</div>
      </div>

      <!-- Main Body -->
      <div class="content">
        @yield('content')
      </div>

      <!-- Footer -->
      <div class="footer">
        <strong>Jeota Media Ltd</strong><br>
        Commercial Film, Video Production &amp; Digital Media · Nairobi, Kenya<br>
        <span style="font-size:11px;color:#B9AFAC">This automated notification was generated by JMOS (Jeota Media Operating System).</span>
      </div>
    </div>
  </div>
</body>
</html>
